### ISSUE TITLE
Install Results in Missing Objects

### ISSUE THREAD

**Issue by DonRichards** [discoverygarden/islandora_solution_pack_manuscript#45]
### Possibly a noob/user error:

**Ran from .../all/modules**

> git clone https://github.com/discoverygarden/islandora_solution_pack_manuscript.git
> drush --yes en islandora_manuscript
> 
> The following extensions will be enabled: islandora_manuscript
> Do you really want to continue? (y/n): y
> WD islandora: Failed to ingest object: islandora:findingAidCModelcode:      [error]
> 401message: Unauthorized
> WD php: RepositoryException: Unauthorized in                                [error]
> RepositoryConnection->parseFedoraExceptions() (line 229 of
> /var/www/drupal/sites/all/libraries/tuque/RepositoryConnection.php).
> Cannot modify header information - headers already sent by (output started  [warning]
> at /usr/share/php/drush/includes/output.inc:37) bootstrap.inc:1232
> RepositoryException: Unauthorized in RepositoryConnection->parseFedoraExceptions() (line 229 of /var/www/drupal/sites/all/libraries/tuque/RepositoryConnection.php).
> Drush command terminated abnormally due to an unrecoverable error.          [error]
### Within the GUI .../admin/islandora/solution_pack_config/solution_packs

**Object status: Some objects are missing and must be installed. See objects list for details.**
- Finding Aid Content Model islandora:findingAidCModel   Missing
- Manuscript Content Model  islandora:manuscriptCModel   Missing
- Manuscript Page Content Model islandora:manuscriptPageCModel   Missing
- Transform Content Model   islandora:transformCModel    Missing
- Manuscript Collection islandora:manuscriptCollection   Missing
- Transform Collection  islandora:transformCollection    Missing
- Default Transform islandora:defaultTransform   Missing

**Comment by jordandukart** [comment]
Need to `drush -u 1` otherwise authentication fails with Fedora (401s).
