### ISSUE TITLE
Readme file - possible documentation source

### ISSUE THREAD

**Issue by bondjimbond** [discoverygarden/islandora_solution_pack_manuscript#47]
Under the Configuration heading, suggest linking to (or pulling content from) this slideshare from CT Digital Archive: http://www.slideshare.net/CTDigitalArchive/how-to-use-the-manuscript-content-model

**Comment by jordandukart** [comment]
Hello,

This has been linked to from the README: https://github.com/discoverygarden/islandora_solution_pack_manuscript/pull/48.

Thanks!
