### ISSUE TITLE
New Manuscript objects should have "mixed materials" as the default value.

### ISSUE THREAD

**Issue by wgilling** [discoverygarden/islandora_solution_pack_manuscript#51]
According to how I interpret the MODS standards, the typeOfResource for manuscript objects should most-likely be "mixed materials" (see:  https://www.loc.gov/standards/mods/userguide/typeofresource.html).

The default_value used in the XML Forms code for new manuscript objects is set to "still image" (see: https://github.com/discoverygarden/islandora_solution_pack_manuscript/blob/7.x/data/forms/islandora_manuscript_form_mods.xml#L260).

I will make a pull request within github for this simple change after creating this issue.

**Comment by adam-vessey** [comment]
Looks good, merged the [referencing PR](https://github.com/discoverygarden/islandora_solution_pack_manuscript/pull/52).

Thank you for your contribution.
