### ISSUE TITLE
Error in Islandora 7.x-1.10

### ISSUE THREAD

**Issue by petermacdonald** [discoverygarden/islandora_solution_pack_manuscript#61]
I'm a volunteer testing the 7.x-1.10 modules of Islandora. We use the Manuscript Solution Pack extensively here and have done so successfully for a long time on 7.x-1.8.

Unfortunately, in 7.x-1.10 I'm get this "debug" message about the islandora_openseadragon_viewer.

User deprecated function: The parameter 'fedora_object' in theme('islandora_openseadragon_viewer') has been deprecated. As of 7.x-1.10, please update your code before the next release. in template_preprocess_islandora_openseadragon_viewer() (line 19 of /var/www/drupal/sites/all/modules/islandora_openseadragon/theme/theme.inc).

User deprecated function: The parameter 'uri' in theme('islandora_openseadragon_viewer') has been deprecated. As of 7.x-1.10, please update your code before the next release. in template_preprocess_islandora_openseadragon_viewer() (line 25 of /var/www/drupal/sites/all/modules/islandora_openseadragon/theme/theme.inc).

Also, The page navigation arrows do not move between pages anymore. I'm wondering if this issue is related to the "debug" error.

Are these two issues going to be addressed in the code of the Manuscript Solution Pack any time soon?

These issues are blocking us from updating our Islandora modules at this time and we do want to do so eventually.

Thanks,
Peter MacDonald

**Comment by adam-vessey** [comment]
These are being addressed in https://github.com/discoverygarden/islandora_paged_tei_seadragon/pull/15

**Comment by willtp87** [comment]
I think this is handled on HEAD.
