### ISSUE TITLE
The id used in islandora-manuscript-manuscript.tpl.php causes bookreader to not be able to use fullscreen toggle

### ISSUE THREAD

**Issue by wgilling** [discoverygarden/islandora_solution_pack_manuscript#63]
I have traced this down to the islandora_internet_archive_bookreader/js/islandora_book_reader.js code where it is setting the elements to 100% height, but the template used for manuscripts uses a different id.  The bookreader expects the wrapping id to be "book-viewer".  See https://github.com/Islandora/islandora_internet_archive_bookreader/blob/7.x/js/islandora_book_reader.js#L505 (referenced "$('div#book-viewer')" this way in several places).

To easily address this, I changed my template to simply use the id of book-viewer even though this is being used for a manuscript because I feel that the javascript code should not have to distinguish between multiple paged-content types.

I could make a pull request with this change in it if needed -- please let me know.

**Comment by fuel37** [comment]
Thanks for letting us know! We'll create a ticket in our internal system to address this.
